---
- name: Check if helm is installed
  shell: |
    command -v helm
  register: helm_installed
  changed_when: false
  failed_when: false

- name: Download Helm 3.17.4 archive
  get_url:
    url: "https://get.helm.sh/helm-v3.17.4-linux-{{ 'arm64' if ansible_architecture in ['aarch64', 'arm64'] else 'amd64' }}.tar.gz"
    dest: /tmp/helm-v3.17.4.tar.gz
    mode: "0644"
  when: helm_installed.rc != 0

- name: Extract Helm archive
  unarchive:
    src: /tmp/helm-v3.17.4.tar.gz
    dest: /tmp
    remote_src: true
  when: helm_installed.rc != 0

- name: Install Helm 3.17.4
  copy:
    src: "/tmp/linux-{{ 'arm64' if ansible_architecture in ['aarch64', 'arm64'] else 'amd64' }}/helm"
    dest: /usr/local/bin/helm
    mode: "0755"
    remote_src: true
  when: helm_installed.rc != 0
