---
- name: Check if podman is installed
  shell: |
    command -v podman
  register: podman_installed
  changed_when: false
  failed_when: false

- name: Install Podman and runtime dependencies from Rocky repositories
  dnf:
    name:
      - podman
      - containernetworking-plugins
      - fuse-overlayfs
      - slirp4netns
    state: present
    update_cache: true
  when: podman_installed.rc != 0
