declare -A CLUSTER1_CONFIG
declare -A CLUSTER2_CONFIG

# COMMON VARIABLE (Please change the value of the variables below.)
CLUSTER1_CONFIG[CTX]="{cluster1 context name}"                                  # Cluster1 Context Name
CLUSTER1_CONFIG[MASTER_NODE_IP]="{cluster1 master node public ip}"              # Cluster1 Master Node Public IP
CLUSTER1_CONFIG[API_SERVER]="https://${CLUSTER1_CONFIG[MASTER_NODE_IP]}:6443"   # Cluster1 API Server
CLUSTER1_CONFIG[STORAGECLASS]="cp-storageclass"                                 # Cluster1 StorageClass Name
CLUSTER1_CONFIG[IAAS_TYPE]="1"                                                  # Cluster1 Cluster IaaS Type ([1] AWS, [2] OPENSTACK, [3] NAVER, [4] NHN, [5] KT)

CLUSTER2_CONFIG[CTX]="{cluster2 context name}"                                  # Cluster2 Context Name
CLUSTER2_CONFIG[MASTER_NODE_IP]="{cluster2 master node public ip}"              # Cluster2 Master Node Public IP
CLUSTER2_CONFIG[API_SERVER]="https://${CLUSTER2_CONFIG[MASTER_NODE_IP]}:6443"   # Cluster2 API Server
CLUSTER2_CONFIG[STORAGECLASS]="cp-storageclass"                                 # Cluster2 StorageClass Name
CLUSTER2_CONFIG[IAAS_TYPE]="1"                                                  # Cluster2 Cluster IaaS Type ([1] AWS, [2] OPENSTACK, [3] NAVER, [4] NHN, [5] KT)

HOST_DOMAIN="{host domain}"                                                     # Host Domain (e.g. xx.xxx.xxx.xx.nip.io)

# The belows are the default values.
# If you change the values below, there will be a problem with the deploy. Please keep the values.
IAAS_TYPE=(
"AWS"
"OPENSTACK"
"NAVER"
"NHN"
"KT"
)

NAMESPACE=(
"openbao"
"mariadb"
"harbor"
"keycloak"
"cp-portal"
"chartmuseum"
"chaos-mesh"
)

CHART_NAME=(
"openbao"
"mariadb"
"harbor"
"keycloak"
"cp-app"
"chartmuseum"
"chaos-mesh"
"cp-cert-setup"
)

declare -A CHART_VERSION=(
  ["openbao"]="0.19.0"
  ["mariadb"]="23.2.1"
  ["harbor"]="1.18.0"
  ["keycloak"]="25.2.0"
  ["cp-app"]="1.7.0"
  ["chartmuseum"]="3.10.4"
  ["chaos-mesh"]="2.8.0"
  ["cp-cert-setup"]="1.0.0"
)

K_PAAS_REGISTRY="registry.k-paas.org"                                                        # k-paas registry
K_PAAS_REPO="kpaas"                                                                          # k-paas repository
K_PAAS_HELM_OCI_REPO="oci://${K_PAAS_REGISTRY}/${K_PAAS_REPO}"                               # k-paas oci helm chart repository
IMAGE_TAGS="v1.7.0"                                                                          # image tag
IMAGE_PULL_POLICY="IfNotPresent"                                                             # image pull policy
IMAGE_PULL_SECRET="cp-regcred"                                                               # image pull secret
SERVICE_TYPE="ClusterIP"                                                                     # service type in kubernetes
SERVICE_PROTOCOL="TCP"                                                                       # service protocol in kubernetes
TLS_SECRET="${HOST_DOMAIN}-tls"                                                              # tls secret

# TLS_CERT
TLS_CERT_AUTO_GENERATED="Y"                                                                  # whether to automatically generate tls cert
TLS_CERT_PATH="path/to/cert/file"                                                            # tls cert file path (if autoGenerated 'N')
TLS_KEY_PATH="path/to/key/file"                                                              # tls key file path (if autoGenerated 'N')

# K8S
K8S_CLUSTER_ADMIN="cp-cluster-admin"                                                         # kubernetes cluster-admin role name
K8S_CLUSTER_ADMIN_NAMESPACE="kube-system"                                                    # kubernetes cluster-admin role namespace

# ISTIO
ISTIO_NAMESPACE="istio-system"                                                               # istio namespace
ISTIO_INGRESSGATEWAY_SELECTOR="istio=ingressgateway"                                         # istio ingressgateway selector
ISTIO_RESOURCE_NAME="cp-portal-istio"                                                        # istio release name for container platform

# SECRETS_MANAGEMENT
## `secmg` is used as a shorthand for secrets management
SECMG_URL="https://openbao.${HOST_DOMAIN}"                                                   # secrets management url
SECMG_ROLE_NAME="cp_role"                                                                    # secrets management role name

# HARBOR
REPOSITORY_URL="https://harbor.${HOST_DOMAIN}"                                               # harbor url
REPOSITORY_USERNAME="admin"                                                                  # harbor admin username (e.g. admin)
REPOSITORY_PASSWORD="Harbor12345"                                                            # harbor admin password (e.g. Harbor12345)
REPOSITORY_PROJECT_NAME="cp-portal-repository"                                               # harbor project name

# CHARTMUSEUM
CHART_REPOSITORY_URL="https://chartmuseum.${HOST_DOMAIN}"                                    # chart repository url
CHART_REPOSITORY_NAME="cp-chart-repository"                                                  # chart repository name

# MARIADB
DATABASE_URL="mariadb.mariadb.svc.cluster.local:3306"                                        # database url
DATABASE_USER_ID="cp-admin"                                                                  # database user name (e.g. cp-admin)
DATABASE_USER_PASSWORD="cpAdmin!12345"                                                       # database user password (e.g. cpAdmin!12345)
DATABASE_TERRAMAN_ID="terraman"                                                              # database user name (e.g. terraman)
DATABASE_TERRAMAN_PASSWORD="cpAdmin!12345"                                                   # database user name (e.g. cpAdmin!12345)

# KEYCLOAK
KEYCLOAK_URL="https://keycloak.${HOST_DOMAIN}"                                               # keycloak url
KEYCLOAK_DB_VENDOR="mariadb"                                                                 # keycloak database vendor
KEYCLOAK_DB_SCHEMA="keycloak"                                                                # keycloak database schema
KEYCLOAK_ADMIN_USERNAME="admin"                                                              # keycloak admin username (e.g. admin)
KEYCLOAK_ADMIN_PASSWORD="admin"                                                              # keycloak admin password (e.g. admin)
KEYCLOAK_SESSIONS_COUNT="2"                                                                  # keycloak sessions count
KEYCLOAK_CP_REALM="cp-realm"                                                                 # keycloak realm for container platform
KEYCLOAK_CP_REALM_ID="6391f3dc-bfc4-4866-ad75-d1458979c964"                                  # keycloak realm id for container platform
KEYCLOAK_CP_CLIENT_ID="cp-client"                                                            # keycloak client id for container platform
KEYCLOAK_CP_CLIENT_SECRET="nddzVVGW9OC6ccy6ULrSMrzdIlqTdv5h"                                 # keycloak client secret for container platform
KEYCLOAK_CP_ADMIN_ID="19724c12-7b3d-4e46-ad3d-9d5bbaf14607"                                  # keycloak container platform admin id

# CP_PORTAL
RELEASE_NAME="cp-portal"                                                                      # container platform portal release name
CP_PORTAL_URL="https://portal.${HOST_DOMAIN}"                                                 # container platform portal url

# CP_SERVICE
CP_SERVICE_PIPELINE_URL="https://pipeline.${HOST_DOMAIN}"                                    # container platform service pipeline url
CP_SERVICE_SOURCE_CONTROL_URL="https://scm.${HOST_DOMAIN}"                                   # container platform service source control url

# CP_CERT_SETUP
CP_CERT_SETUP_NAMESPACE="kube-system"                                                        # container platform cert setup namespace
CP_CERT_SETUP_SELECTOR="app=${CHART_NAME[7]}"                                                # container platform cert setup selector